### ISSUE TITLE
customize bootstrap 3 css

### ISSUE THREAD

**Issue by foodaka** [dbtek/jekyll-bootstrap-3#12]
Sorry if this an obvious question, where do I style the bootstrap css to change the colors and such?

**Comment by dbtek** [comment]
You could do it by customising bootstrap [here](http://getbootstrap.com/customize/), and replace the built-in css [here](https://github.com/dbtek/jekyll-bootstrap-3/tree/master/assets/themes/bootstrap/resources/bootstrap).

**Comment by foodaka** [comment]
thanks for the fast response!

**Comment by dbtek** [comment]
Your welcome!
